--
-- PostgreSQL database dump
--

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.3

-- Started on 2025-11-12 05:28:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16395)
-- Name: BusinessCards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BusinessCards" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Gender" character varying(10),
    "DateOfBirth" date,
    "Email" character varying(200) NOT NULL,
    "Phone" character varying(50) NOT NULL,
    "Photo" text,
    "Address" character varying(500),
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."BusinessCards" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16394)
-- Name: BusinessCards_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BusinessCards" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BusinessCards_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3418 (class 0 OID 16395)
-- Dependencies: 216
-- Data for Name: BusinessCards; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BusinessCards" ("Id", "Name", "Gender", "DateOfBirth", "Email", "Phone", "Photo", "Address", "CreatedAt", "UpdatedAt") FROM stdin;
162	Michael Johnson	Male	1992-09-05	michael.johnson22@example.com	555-456-7890	\N	789 Pine Rd	2025-11-12 00:10:30.545008+00	\N
163	Emily Davis	Female	1998-12-12	emily.davis33@example.com	555-321-4321	\N	101 Maple Blvd	2025-11-12 00:10:30.545013+00	\N
164	William Brown	Male	1987-03-17	william.brown44@example.com	555-654-0987	\N	202 Birch Ln	2025-11-12 00:10:30.545013+00	\N
165	Olivia Wilson	Female	1995-07-22	olivia.wilson55@example.com	555-765-4321	\N	303 Cedar St	2025-11-12 00:10:30.545013+00	\N
166	James Taylor	Male	1991-11-30	james.taylor66@example.com	555-890-1234	\N	404 Elm St	2025-11-12 00:10:30.545014+00	\N
167	Sophia Martinez	Female	1989-05-25	sophia.martinez77@example.com	555-234-5678	\N	505 Spruce Ave	2025-11-12 00:10:30.545014+00	\N
168	Benjamin Anderson	Male	1993-08-14	benjamin.anderson88@example.com	555-678-9012	\N	606 Walnut Rd	2025-11-12 00:10:30.545014+00	\N
169	Ava Thomas	Female	1996-02-09	ava.thomas99@example.com	555-345-6789	\N	707 Chestnut Blvd	2025-11-12 00:10:30.545014+00	\N
\.


--
-- TOC entry 3416 (class 0 OID 16389)
-- Dependencies: 214
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251108233331_CreateBusinessCardTable	9.0.10
\.


--
-- TOC entry 3424 (class 0 OID 0)
-- Dependencies: 215
-- Name: BusinessCards_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."BusinessCards_Id_seq"', 169, true);


--
-- TOC entry 3273 (class 2606 OID 16402)
-- Name: BusinessCards PK_BusinessCards; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BusinessCards"
    ADD CONSTRAINT "PK_BusinessCards" PRIMARY KEY ("Id");


--
-- TOC entry 3269 (class 2606 OID 16393)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3270 (class 1259 OID 16403)
-- Name: IX_BusinessCards_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_BusinessCards_Email" ON public."BusinessCards" USING btree ("Email");


--
-- TOC entry 3271 (class 1259 OID 16404)
-- Name: IX_BusinessCards_Phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_BusinessCards_Phone" ON public."BusinessCards" USING btree ("Phone");


-- Completed on 2025-11-12 05:28:36

--
-- PostgreSQL database dump complete
--

